/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hdfs_wfx_java_WfxPair */

#ifndef _Included_hdfs_wfx_java_WfxPair
#define _Included_hdfs_wfx_java_WfxPair
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hdfs_wfx_java_WfxPair
 * Method:    notifyProgress
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hdfs_1wfx_1java_WfxPair_notifyProgress
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
